[Service]
Environment="LD_LIBRARY_PATH=/home/jakes/Projects/IPU7/libcamera/build/src/libcamera:/home/jakes/Projects/IPU7/libcamera/build/src/libcamera/base"
Environment="LIBCAMERA_LOG_LEVELS=IPU7:0"
Environment="LIBCAMERA_LOG_FILE=/tmp/libcamera-pw.log"
